INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('1', 'Construccion de Software', 10, 1000, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('2', 'Maquinas Abstractas y Lenguajes Formales', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('3', 'Calculo 1', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('4', 'Calculo 2', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('5', 'Modelos Discretos', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('6', 'Diseño de Software', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('7', 'Redes', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('8', 'Redes 2', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('9', 'Algoritmos y Estructuras de Datos', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('10', 'El regreso de Calculo 3', 10, 90, '...', "Deshabilitado");
