INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('1', 'Construccion de Software', 10, 1000, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('2', 'Maquinas Abstractas y Lenguajes Formales', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('3', 'Calculo 1', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('4', 'Calculo 2', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('5', 'Modelos Discretos', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('6', 'Diseño de Software', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('7', 'Redes', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('8', 'Redes 2', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('9', 'Algoritmos y Estructuras de Datos', 10, 90, '...', "Habilitado");
INSERT INTO Curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('10', 'El regreso de Calculo 3', 10, 90, '...', "Deshabilitado");
INSERT INTO syllabus.curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('11', "Introducion a la ICC", 5, 5, "Bienvenido a icc", "Habilitado");
INSERT INTO syllabus.curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('12', "IHC", 5, 5, "Bienvenido a ihc", "Habilitado");
INSERT INTO syllabus.curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('13', "Modelos discretos", 5, 5, "rapa 1", "Habilitado");
INSERT INTO syllabus.curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('14', "Inteligencia artificial", 5, 5, "Cosas locas pasan aquí", "Habilitado");
INSERT INTO syllabus.curso (id, nombre, horasPresenciales, horasAutonomas, descripcion, estado) VALUES ('15', "Proyecto de titulo", 5, 5, "Adios de icc", "Habilitado");